#!/bin/bash
#
# TL Linux Portable USB Setup Script
# Creates a bootable USB drive with full persistence and security
#
# Usage: sudo ./portable-usb-setup.sh /dev/sdX
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Banner
echo -e "${CYAN}"
cat << "EOF"
╔════════════════════════════════════════════════════════════╗
║                                                            ║
║        TL LINUX PORTABLE USB SETUP                         ║
║        ⏰ Time Lord Linux - Take it anywhere!              ║
║                                                            ║
╚════════════════════════════════════════════════════════════╝
EOF
echo -e "${NC}"

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}Error: This script must be run as root (use sudo)${NC}"
   exit 1
fi

# Check arguments
if [ -z "$1" ]; then
    echo -e "${YELLOW}Usage: sudo $0 /dev/sdX${NC}"
    echo ""
    echo "Available devices:"
    lsblk -d -o NAME,SIZE,TYPE,TRAN | grep -E "disk.*usb"
    exit 1
fi

USB_DEVICE="$1"

# Verify device exists
if [ ! -b "$USB_DEVICE" ]; then
    echo -e "${RED}Error: Device $USB_DEVICE not found${NC}"
    exit 1
fi

# Get device info
DEVICE_SIZE=$(lsblk -b -d -n -o SIZE "$USB_DEVICE" | numfmt --to=iec-i --suffix=B)
DEVICE_MODEL=$(lsblk -d -n -o MODEL "$USB_DEVICE" || echo "Unknown")

echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}Selected Device:${NC} $USB_DEVICE"
echo -e "${GREEN}Model:${NC} $DEVICE_MODEL"
echo -e "${GREEN}Size:${NC} $DEVICE_SIZE"
echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
echo ""

# Warning
echo -e "${RED}⚠️  WARNING ⚠️${NC}"
echo -e "${YELLOW}This will ERASE ALL DATA on $USB_DEVICE!${NC}"
echo -e "${YELLOW}Make sure you have selected the correct device!${NC}"
echo ""
read -p "Type 'YES' to continue: " confirmation

if [ "$confirmation" != "YES" ]; then
    echo -e "${YELLOW}Aborted by user.${NC}"
    exit 0
fi

echo ""
echo -e "${GREEN}Starting USB setup...${NC}"
echo ""

# Unmount any mounted partitions
echo -e "${BLUE}[1/10]${NC} Unmounting existing partitions..."
umount ${USB_DEVICE}* 2>/dev/null || true
sleep 1

# Wipe existing partition table
echo -e "${BLUE}[2/10]${NC} Wiping partition table..."
wipefs -a "$USB_DEVICE"
dd if=/dev/zero of="$USB_DEVICE" bs=1M count=10 status=none
sleep 2

# Create new partition table (GPT for UEFI support)
echo -e "${BLUE}[3/10]${NC} Creating GPT partition table..."
parted -s "$USB_DEVICE" mklabel gpt

# Create partitions
echo -e "${BLUE}[4/10]${NC} Creating partitions..."

# Partition 1: EFI System Partition (512MB)
parted -s "$USB_DEVICE" mkpart "EFI" fat32 1MiB 513MiB
parted -s "$USB_DEVICE" set 1 esp on

# Partition 2: Boot partition (1GB)
parted -s "$USB_DEVICE" mkpart "BOOT" ext4 513MiB 1537MiB

# Partition 3: Root partition (10GB)
parted -s "$USB_DEVICE" mkpart "ROOT" ext4 1537MiB 11537MiB

# Partition 4: Home/Persistence partition (remaining space)
parted -s "$USB_DEVICE" mkpart "HOME" ext4 11537MiB 100%

# Refresh partition table
partprobe "$USB_DEVICE"
sleep 2

# Format partitions
echo -e "${BLUE}[5/10]${NC} Formatting partitions..."

# EFI partition
mkfs.vfat -F 32 -n "TL_EFI" "${USB_DEVICE}1"

# Boot partition
mkfs.ext4 -F -L "TL_BOOT" "${USB_DEVICE}2"

# Root partition
mkfs.ext4 -F -L "TL_ROOT" "${USB_DEVICE}3"

# Home partition
mkfs.ext4 -F -L "TL_HOME" "${USB_DEVICE}4"

# Create mount points
echo -e "${BLUE}[6/10]${NC} Creating mount points..."
MOUNT_POINT="/mnt/tl-usb-setup"
mkdir -p "$MOUNT_POINT"

# Mount partitions
echo -e "${BLUE}[7/10]${NC} Mounting partitions..."
mount "${USB_DEVICE}3" "$MOUNT_POINT"
mkdir -p "$MOUNT_POINT/boot"
mkdir -p "$MOUNT_POINT/boot/efi"
mkdir -p "$MOUNT_POINT/home"
mount "${USB_DEVICE}2" "$MOUNT_POINT/boot"
mount "${USB_DEVICE}1" "$MOUNT_POINT/boot/efi"
mount "${USB_DEVICE}4" "$MOUNT_POINT/home"

# Install base system (if ISO is available)
echo -e "${BLUE}[8/10]${NC} Setting up boot configuration..."

# Create directory structure
mkdir -p "$MOUNT_POINT/etc"
mkdir -p "$MOUNT_POINT/usr/bin"

# Create fstab for persistence
cat > "$MOUNT_POINT/etc/fstab" << EOF
# TL Linux Portable USB - fstab
# Generated by portable-usb-setup.sh

LABEL=TL_ROOT    /           ext4    defaults,noatime    0 1
LABEL=TL_BOOT    /boot       ext4    defaults,noatime    0 2
LABEL=TL_EFI     /boot/efi   vfat    umask=0077          0 1
LABEL=TL_HOME    /home       ext4    defaults,noatime    0 2

# Tmpfs for better performance
tmpfs           /tmp        tmpfs   defaults,noatime,mode=1777  0 0
EOF

echo -e "${GREEN}✓ Partition layout configured${NC}"

# Create persistence configuration
echo -e "${BLUE}[9/10]${NC} Configuring persistence..."
cat > "$MOUNT_POINT/persistence.conf" << EOF
# TL Linux Persistence Configuration
/home
/etc
/var/log
/usr/local
/opt
EOF

# Create README
cat > "$MOUNT_POINT/README-TL-LINUX.txt" << EOF
═══════════════════════════════════════════════════════════════
    TL LINUX - PORTABLE USB DRIVE
═══════════════════════════════════════════════════════════════

This USB drive contains a portable TL Linux operating system
with full persistence and security features.

FEATURES:
---------
✓ Full UEFI and Legacy BIOS support
✓ Persistent storage - all changes are saved
✓ Secure and encrypted storage (optional)
✓ Accessibility-first design
✓ ADHD and wellbeing support
✓ Complete desktop environment

BOOT INSTRUCTIONS:
------------------
1. Insert USB drive into computer
2. Restart computer
3. Press boot menu key (usually F12, F2, ESC, or DEL)
4. Select this USB drive from boot menu
5. TL Linux will start automatically

PARTITION LAYOUT:
-----------------
Partition 1: EFI System (512MB) - Boot files for UEFI
Partition 2: Boot (1GB) - Kernel and boot configuration
Partition 3: Root (10GB) - Operating system
Partition 4: Home (remaining) - Your files and settings

ENCRYPTION (Optional):
---------------------
To encrypt your home partition for additional security:

  sudo cryptsetup luksFormat ${USB_DEVICE}4
  sudo cryptsetup luksOpen ${USB_DEVICE}4 tl_home
  sudo mkfs.ext4 /dev/mapper/tl_home

Then update /etc/fstab and /etc/crypttab accordingly.

FIRST RUN:
----------
On first boot, TL Linux will guide you through:
- User account setup
- Accessibility preferences
- Theme selection
- Application configuration

REQUIREMENTS:
-------------
- Minimum 16GB USB drive (32GB+ recommended)
- UEFI or BIOS boot support
- 2GB RAM minimum (4GB+ recommended)
- USB 3.0 for best performance

SUPPORT:
--------
For documentation and support:
https://github.com/TimeLordHorus/TimeLordHorus

═══════════════════════════════════════════════════════════════
                TL Linux - Accessibility First
═══════════════════════════════════════════════════════════════
EOF

# Create boot configuration placeholder
mkdir -p "$MOUNT_POINT/boot/grub"
cat > "$MOUNT_POINT/boot/grub/grub.cfg" << 'EOF'
# TL Linux GRUB Configuration
# This file will be generated during ISO installation

set timeout=10
set default=0

menuentry "TL Linux - Portable Mode" {
    linux /vmlinuz boot=live persistence
    initrd /initrd.img
}

menuentry "TL Linux - Safe Mode" {
    linux /vmlinuz boot=live persistence nomodeset
    initrd /initrd.img
}
EOF

# Optimization for USB drives
echo -e "${BLUE}[10/10]${NC} Optimizing for USB drive performance..."

# Disable journaling on ext4 (optional, for better USB performance)
tune2fs -O ^has_journal "${USB_DEVICE}3"
tune2fs -O ^has_journal "${USB_DEVICE}4"

# Set noatime mount option (reduces writes)
echo -e "${GREEN}✓ Filesystem optimization complete${NC}"

# Unmount
echo ""
echo -e "${BLUE}Finalizing...${NC}"
sync
umount -R "$MOUNT_POINT" 2>/dev/null || true
rmdir "$MOUNT_POINT"

# Success message
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}✓ USB DRIVE SETUP COMPLETE!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${CYAN}Partition Layout:${NC}"
lsblk "$USB_DEVICE" -o NAME,SIZE,TYPE,FSTYPE,LABEL
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo -e "  1. Install TL Linux ISO to the USB drive:"
echo -e "     ${CYAN}sudo ./installer/install-tl-linux.sh --usb $USB_DEVICE${NC}"
echo ""
echo -e "  2. Or use the build system:"
echo -e "     ${CYAN}make usb USB_DEVICE=$USB_DEVICE${NC}"
echo ""
echo -e "${GREEN}Your portable TL Linux USB is ready!${NC}"
echo -e "${BLUE}Boot from this drive on any compatible computer.${NC}"
echo ""

# Optional encryption info
echo -e "${YELLOW}═══════════════════════════════════════════════════════${NC}"
echo -e "${YELLOW}Security Tip:${NC}"
echo -e "To encrypt your home partition (${USB_DEVICE}4):"
echo -e "  ${CYAN}sudo cryptsetup luksFormat ${USB_DEVICE}4${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════${NC}"
echo ""

exit 0
